[package]
name = "simple"
version = "0.1.0"
authors = ["DaanA32 <daan32@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mesh-generation = { path = "../../", version = "0.1.4" }
